### ISSUE TITLE
Fails to run custom build command for `libsodium-sys v0.0.16`

### ISSUE THREAD

**Issue by andrerfneves** [yeletech/libbolt#3]
### Might be a libsodium issue
> New to libsodium, so if this is clearly a libsodium issue, let me know and I'll attempt to solve it through other routes. 

### General Info
> OSX running High Sierra 10.13.4
> Installed libsodium and configured/built binary locally (seemingly without hiccups)

<img width="1680" alt="screen shot 2018-08-15 at 3 20 10 pm" src="https://user-images.githubusercontent.com/2574011/44168498-7bad4f80-a09f-11e8-92de-ff8414289598.png">

### Issue
When running `make` or `make test` or `make bench` on the `libbolt` root, I run into this issue:
> error: failed to run custom build command for `libsodium-sys v0.0.16`

<img width="1680" alt="screen shot 2018-08-15 at 3 26 27 pm" src="https://user-images.githubusercontent.com/2574011/44168546-a39cb300-a09f-11e8-835e-4895a047f798.png">

I'm using latest stable libsodium which is found here. Can `stable` be the issue? Should I attempt with the 1.0.16 version instead?

<img width="705" alt="screen shot 2018-08-15 at 3 28 06 pm" src="https://user-images.githubusercontent.com/2574011/44168614-e52d5e00-a09f-11e8-933b-4ab2250c22a0.png">

I'm continuing to attempt a few things myself in order to resolve it but any pointers would be greatly appreciated.

**Comment by jakinyele** [comment]
Looking into this. Thanks for reporting!

**Comment by jakinyele** [comment]
What happens when you do: `pkg-config --libs --cflags libsodium`? If you get an error then, you are just missing pkg-config. You can install it via homebrew: `brew install pkg-config`. You'll also need to install libsodium by following the instructions provided in the README.

**Comment by andrerfneves** [comment]
<img width="633" alt="screen shot 2018-08-18 at 7 59 43 pm" src="https://user-images.githubusercontent.com/2574011/44304135-50d22e00-a321-11e8-9297-3487c655d35b.png">

Just like that. Thanks!
